In [2]:
import csv
myList = []
with open('C:/Users/Sorina/Downloads/iris.data') as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',')
    for row in readCSV:
         if len(row) == 5:
            myList.append([float(row[0]), float(row[1]), float(row[2]), float(row[3])])

import numpy as np
npArray = np.array(myList)
print(npArray)

#col0_min = np.min(npArray[:,0])
#col0_norm = (npArray[:,0]-min(npArray[:,0])) / (max(npArray[:,0])-min(npArray[:,0]))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [50]:
min0=np.min(npArray[:,0])
max0=np.max(npArray[:,0])
media0=np.median(npArray[:,0])
mediana0=np.average(npArray[:,0])
col0_norm = (npArray[:,0]-min(npArray[:,0])) / (max(npArray[:,0])-min(npArray[:,0]))

print("Numarul maxim de pe coloana 1: ", max0,"\nNumarul minim de pe coloana 1: ", min0,"\nMedia de pe coloana 1: ", media0,"\nMediana1: ",mediana0 )
#print("\nValorile normalizare1: ",col0_norm)               

Numarul maxim de pe coloana 1:  7.9 
Numarul minim de pe coloana 1:  4.3 
Media de pe coloana 1:  5.8 
Mediana1:  5.843333333333334


In [94]:
min1=np.min(npArray[:,1])
max1=np.max(npArray[:,1])
media1=np.median(npArray[:,1])
mediana1=np.average(npArray[:,1])
col1_norm = (npArray[:,1]-min(npArray[:,1])) / (max(npArray[:,1])-min(npArray[:,1]))

print("Numarul maxim de pe coloana 2: ", max1,"\nNumarul minim de pe coloana 2: ", min1,"\nMedia de pe coloana 2: ", media1,"\nMediana2: ",mediana1 )
#print("\nValorile normalizare2: ",col1_norm)    

Numarul maxim de pe coloana 2:  4.4 
Numarul minim de pe coloana 2:  2.0 
Media de pe coloana 2:  3.0 
Mediana2:  3.0540000000000003


In [51]:
min2=np.min(npArray[:,2])
max2=np.max(npArray[:,2])
media2=np.median(npArray[:,2])
mediana2=np.average(npArray[:,2])
col2_norm = (npArray[:,2]-min(npArray[:,2])) / (max(npArray[:,2])-min(npArray[:,2]))

print("Numarul maxim de pe coloana 3: ", max2,"\nNumarul minim de pe coloana 3: ", min2,"\nMedia de pe coloana 3: ", media2,"\nMediana3: ",mediana2 )
#print("\nValorile normalizare3: ",col2_norm)    

Numarul maxim de pe coloana 3:  6.9 
Numarul minim de pe coloana 3:  1.0 
Media de pe coloana 3:  4.35 
Mediana3:  3.758666666666666


In [52]:
min3=np.min(npArray[:,3])
max3=np.max(npArray[:,3])
media3=np.median(npArray[:,3])
mediana3=np.average(npArray[:,3])
col3_norm = (npArray[:,3]-min(npArray[:,3])) / (max(npArray[:,3])-min(npArray[:,3]))

print("Numarul maxim de pe coloana 4: ", max3,"\nNumarul minim de pe coloana 4: ", min3,"\nMedia de pe coloana 4: ", media3, "\nMediana4: ",mediana3)
#print("\nValorile normalizare4: ",col3_norm)    

Numarul maxim de pe coloana 4:  2.5 
Numarul minim de pe coloana 4:  0.1 
Media de pe coloana 4:  1.3 
Mediana4:  1.1986666666666668


In [53]:
npArrayNorm=np.stack((col0_norm,col1_norm,col2_norm,col3_norm),axis=1)
print(npArrayNorm)

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.22222222 

In [93]:
#pond=[0.2,1.1,-0.9,1]
col4=[]
for i in range(0,150):
    suma_pondere=0.2*npArray[i,0]+1.1*npArray[i,1]-0.9*npArray[i,2]+1*npArray[i,3]
    col4.append(suma_pondere)
np_col4=np.array(col4)
pond_array=np.insert(npArray,4,np_col4,axis=1)
print(pond_array)


[[5.1  3.5  1.4  0.2  3.81]
 [4.9  3.   1.4  0.2  3.22]
 [4.7  3.2  1.3  0.2  3.49]
 [4.6  3.1  1.5  0.2  3.18]
 [5.   3.6  1.4  0.2  3.9 ]
 [5.4  3.9  1.7  0.4  4.24]
 [4.6  3.4  1.4  0.3  3.7 ]
 [5.   3.4  1.5  0.2  3.59]
 [4.4  2.9  1.4  0.2  3.01]
 [4.9  3.1  1.5  0.1  3.14]
 [5.4  3.7  1.5  0.2  4.  ]
 [4.8  3.4  1.6  0.2  3.46]
 [4.8  3.   1.4  0.1  3.1 ]
 [4.3  3.   1.1  0.1  3.27]
 [5.8  4.   1.2  0.2  4.68]
 [5.7  4.4  1.5  0.4  5.03]
 [5.4  3.9  1.3  0.4  4.6 ]
 [5.1  3.5  1.4  0.3  3.91]
 [5.7  3.8  1.7  0.3  4.09]
 [5.1  3.8  1.5  0.3  4.15]
 [5.4  3.4  1.7  0.2  3.49]
 [5.1  3.7  1.5  0.4  4.14]
 [4.6  3.6  1.   0.2  4.18]
 [5.1  3.3  1.7  0.5  3.62]
 [4.8  3.4  1.9  0.2  3.19]
 [5.   3.   1.6  0.2  3.06]
 [5.   3.4  1.6  0.4  3.7 ]
 [5.2  3.5  1.5  0.2  3.74]
 [5.2  3.4  1.4  0.2  3.72]
 [4.7  3.2  1.6  0.2  3.22]
 [4.8  3.1  1.6  0.2  3.13]
 [5.4  3.4  1.5  0.4  3.87]
 [5.2  4.1  1.5  0.1  4.3 ]
 [5.5  4.2  1.4  0.2  4.66]
 [4.9  3.1  1.5  0.1  3.14]
 [5.   3.2  1.2  0.2