In [8]:
#regula delta
import numpy as np
#1. citire y si d
x=np.array([[45,85,-1],[50,43,-1],[40,80,-1],[55,42,-1],[200,43,-1],[48,40,-1],[195,41,-1],[43,87,-1],[190,40,-1]])
w=np.array([[1,-1,-1],[1,1,-1],[-1,1,-1 ]])
d=[[1,-1,-1],[-1,1,-1],[1,-1,-1],[-1,1,-1],[-1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,-1],[-1,-1,1]]
c=0.2
Emax=20
ok=0
while ok==0:
    E=0
    for i in range(9):
        Ep=0
        net=[0,0,0]
        o=[0,0,0]
        print("IESIREA ",i,"->",x[i])
        for k in range(3):
            net=w[k].dot(x[i])
            o[k]=2/(1+np.exp(-1*net))-1
        for j in range(3):
            w[j]=w[j]+c*(d[i][j]-o[j])*(1-o[j]**2)*x[i] 
            Ep=Ep+((d[i][j]-o[j])**2)/2
        E=E+Ep
        print(E)
        print("w:",w)
    if E>Emax:
        ok=0
    else:
        ok=1

IESIREA  0 -> [45 85 -1]
6.0
w: [[ 1 -1 -1]
 [ 1  1 -1]
 [-1  1 -1]]
IESIREA  1 -> [50 43 -1]
7.998671052128104
w: [[ 0 -1  0]
 [ 1  1 -1]
 [-1  0  0]]
IESIREA  2 -> [40 80 -1]
11.998671052128104
w: [[ 0 -1  0]
 [ 1  1 -1]
 [-1  0  0]]
IESIREA  3 -> [55 42 -1]
11.998671052128104
w: [[ 0 -1  0]
 [ 1  1 -1]
 [-1  0  0]]
IESIREA  4 -> [200  43  -1]
11.998671052128104
w: [[ 0 -1  0]
 [ 1  1 -1]
 [-1  0  0]]
IESIREA  5 -> [48 40 -1]
11.998671052128104
w: [[ 0 -1  0]
 [ 1  1 -1]
 [-1  0  0]]
IESIREA  6 -> [195  41  -1]
15.998671052128104
w: [[ 0 -1  0]
 [ 1  1 -1]
 [-1  0  0]]
IESIREA  7 -> [43 87 -1]
19.998671052128103
w: [[ 0 -1  0]
 [ 1  1 -1]
 [-1  0  0]]
IESIREA  8 -> [190  40  -1]
23.998671052128103
w: [[ 0 -1  0]
 [ 1  1 -1]
 [-1  0  0]]
IESIREA  0 -> [45 85 -1]
4.0
w: [[ 0 -1  0]
 [ 1  1 -1]
 [-1  0  0]]
IESIREA  1 -> [50 43 -1]
4.0
w: [[ 0 -1  0]
 [ 1  1 -1]
 [-1  0  0]]
IESIREA  2 -> [40 80 -1]
8.0
w: [[ 0 -1  0]
 [ 1  1 -1]
 [-1  0  0]]
IESIREA  3 -> [55 42 -1]
8.0
w: [[ 0 -1  0]
